### ISSUE TITLE
Mermaid diagrams validation in CI

### ISSUE THREAD

**Issue by HonzaR** [zodl-inc/zodl-android#628]
## Is your feature request related to a problem? Please describe.
We'd like to avoid broken diagrams in our documentation (e.g. [Architecture.md](https://github.com/zcash/secant-android-wallet/blob/main/docs/Architecture.md)). It would simplify the reviewer work when we provide a new PR-triggered action to validate our Mermaid diagrams.

## Describe the solution you'd like
An extra action running the Mermaid CLI on our markdown file as described here would be a sufficient solution - [Mermaid CLI](https://github.com/mermaid-js/mermaid-cli#transform-a-markdown-file-with-mermaid-diagrams).

## Additional context:
```
lint_css:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.x'
      - name: Install csstree
        timeout-minutes: 4
        run: |
          npm install -g csstree-validator
      - name: Validate CSS
        timeout-minutes: 1
        continue-on-error: true
        run: |
          csstree-validator browserApp/src/jsMain/resources/asset/css/impulse.css
```
```
 name: Block Arbitrary Code Execution
  shell: bash
  run: |
    yarn config set ignore-scripts true
    npm config set ignore-scripts true
```
